---
certResolver: le-staging

fqdn: ""

etherpad:
  resources: {}

jitsi-meet:
  publicURL: ""

  tz: Asia/Shanghai

  web:
    extraEnvs:
      ETHERPAD_URL_BASE: ""
    ingress:
      enabled: false

  jicofo:
    livenessProbe:
      failureThreshold: 30
      periodSeconds: 10
    readinessProbe:
      failureThreshold: 30
      periodSeconds: 10

  jvb:
    service:
      # enabled: true
      type: NodePort
    UDPPort: 30000

    livenessProbe:
      failureThreshold: 30
      periodSeconds: 10
    readinessProbe:
      failureThreshold: 30
      periodSeconds: 10

    websockets:
      enabled: true

    publicIP: ""
